#!/usr/bin/env bash

EVOP_COMMON_METADATA_ARGS=()

evop_build_common_metadata_args() {
    local prompt_source="$1"
    local artifacts_root="$2"

    EVOP_COMMON_METADATA_ARGS=(
        AGENT "$AGENT"
        LANGUAGE_PROFILE "$LANGUAGE_PROFILE"
        LANGUAGE_PROFILE_SOURCE "$LANGUAGE_PROFILE_SOURCE"
        FRAMEWORK_PROFILE "$FRAMEWORK_PROFILE"
        FRAMEWORK_PROFILE_SOURCE "$FRAMEWORK_PROFILE_SOURCE"
        PROJECT_TYPE "$PROJECT_TYPE"
        PROJECT_TYPE_SOURCE "$PROJECT_TYPE_SOURCE"
        PACKAGE_MANAGER "$EVOP_PROJECT_CONTEXT_PACKAGE_MANAGER"
        WORKSPACE_MODE "$EVOP_PROJECT_CONTEXT_WORKSPACE_MODE"
        DEV_COMMAND "$EVOP_PROJECT_CONTEXT_DEV_COMMAND"
        BUILD_COMMAND "$EVOP_PROJECT_CONTEXT_BUILD_COMMAND"
        TEST_COMMAND "$EVOP_PROJECT_CONTEXT_TEST_COMMAND"
        LINT_COMMAND "$EVOP_PROJECT_CONTEXT_LINT_COMMAND"
        TYPECHECK_COMMAND "$EVOP_PROJECT_CONTEXT_TYPECHECK_COMMAND"
        SEARCH_ROOTS "$EVOP_PROJECT_CONTEXT_SEARCH_ROOTS"
        TASK_KIND "$EVOP_PROJECT_CONTEXT_TASK_KIND"
        SEARCH_STRATEGY "$EVOP_PROJECT_CONTEXT_SEARCH_STRATEGY"
        EDIT_STRATEGY "$EVOP_PROJECT_CONTEXT_EDIT_STRATEGY"
        VERIFICATION_STRATEGY "$EVOP_PROJECT_CONTEXT_VERIFICATION_STRATEGY"
        RISK_FOCUS "$EVOP_PROJECT_CONTEXT_RISK_FOCUS"
        TARGET_DIR "$TARGET_DIR"
        ARTIFACTS_ROOT "$artifacts_root"
        PROMPT_SOURCE "$prompt_source"
    )
}
